const { CATEGORIES } = require("./consts");

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// By default, Docusaurus generates a sidebar from the docs folder structure
// tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
// @see https://docusaurus.io/docs/sidebar#sidebar-item-category

/**
 * Get sidebar config for category
 * @remark Generates parent category with children as subitems
 * @param {string} category
 * @example getSidebar("reference")
 */
const getSidebar = (category) => [
    {
        type: "category",
        label: CATEGORIES[category],
        link: { type: "doc", id: `${category}/index` },
        items: [{ type: "autogenerated", dirName: category }],
        collapsible: false,
    },
];

// TODO: [FSDCUR] Add sidebar items description (https://docusaurus.io/blog/releases/2.4#sidebar-item-description)
module.exports = {
    getstartedSidebar: getSidebar("get-started"),
    guidesSidebar: getSidebar("guides"),
    referenceSidebar: getSidebar("reference"),
    aboutSidebar: getSidebar("about"),
};
