const { CATEGORIES } = require("./consts");

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// By default, Docusaurus generates a sidebar from the docs folder structure
// tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
// @see https://docusaurus.io/docs/sidebar#sidebar-item-category

/**
 * Get sidebar config for category
 * @remark Generates parent category with children as subitems
 * @param {string} category
 * @example getSidebar("reference")
 */
const getSidebar = (category) => [
    {
        type: "category",
        label: CATEGORIES[category],
        items: [{ type: "autogenerated", dirName: category }],
        collapsible: false,
    },
];

module.exports = {
    docsSidebar: [
        ...getSidebar("get-started"),
        ...getSidebar("guides"),
        ...getSidebar("reference"),
        ...getSidebar("about"),
    ],
};
