import type { Example } from "@site/src/entities/example";

export const VERSIONS = {
    V0: "v0",
    V1: "v1",
    V2: "v2",
};

/**
 * List of site examples
 * @remark Add site here only if you're sure that its allowed to share website link / codebase
 * @example How to add new site?
 * 1. Add new item in `examples` const
 * 2. Fill details (required with "*"):
 *  - *title (should be unique)
 *  - *description (shortly)
 *  - *preview (image preview - `/pages/examples/img/{YOUR_SITE}.[png|jpg|jpeg]`)
 *  - *updatetAt (date of adding on examples list, for highlighting first two weeks)
 *  - *version (FSD version which implemented in your codebase)
 *  - website, source (links for your site)
 *  - tech (e.g. used UIKit/state-management tech)
 * 3. Profit!
 */
export const examples: Example[] = [
    {
        title: "Cardbox",
        description: "The best solutions from developers in one place",
        source: "https://github.com/cardbox/frontend",
        preview: require("./img/cardbox.png"),
        version: VERSIONS.V2,
        updatedAt: "2021-11-12",
        tech: ["react", "effector"],
    },
    {
        title: "Github Client",
        description: "React & GraphQL powered github web-client",
        source: "https://github.com/ani-team/github-client/tree/workshop/feature-sliced-next",
        preview: require("./img/github-client.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-04-26",
        tech: ["react", "graphql", "antd"],
    },
    {
        title: "Todo App (React+Effector)",
        description:
            "QuickStart todo-app example for React developers (Effector version)",
        website: "https://7b64m.csb.app/",
        source: "https://github.com/feature-sliced/examples/tree/master/todo-app",
        preview: require("./img/todo-app-react-effector.png"),
        version: VERSIONS.V2,
        updatedAt: "2021-07-05",
        tech: ["react", "effector", "antd"],
    },
    {
        title: "Todo App (React+Redux)",
        description:
            "QuickStart todo-app example for React developers (Redux version)",
        source: "https://github.com/EliseyMartynov/fs-rtk",
        preview: require("./img/todo-app-react-redux.png"),
        version: VERSIONS.V2,
        updatedAt: "2022-09-06",
        tech: ["react", "redux", "antd"],
    },
    {
        title: "Todo App (Vue 3)",
        description: "QuickStart todo-app example for Vue developers",
        source: "https://github.com/EliseyMartynov/fs-vue",
        preview: require("./img/todo-app-vue.png"),
        version: VERSIONS.V2,
        updatedAt: "2021-12-27",
        tech: ["vue", "vuex", "antd"],
    },
    {
        title: "Todo App (Angular 13)",
        description: "QuickStart todo-app example for Angular developers",
        website: "https://angular-feature-sliced-architecture.netlify.app/",
        source: "https://github.com/Affiction/angular-feature-sliced",
        preview: require("./img/todo-app-angular.png"),
        version: VERSIONS.V2,
        updatedAt: "2022-01-31",
        tech: ["angular", "rxjs"],
    },
    {
        title: "Sharead (demo)",
        description: "Book Marketplace",
        website: "https://dev-sharead.netlify.app/",
        source: "https://github.com/select-name/sharead-frontend",
        preview: require("./img/sharead.png"),
        version: VERSIONS.V2,
        updatedAt: "2021-11-06",
        tech: ["react", "effector", "antd"],
    },
    {
        title: "Projentry (demo)",
        description: "Assistant for your projects",
        website: "https://projentry.netlify.app/",
        source: "https://github.com/ani-team/projentry",
        preview: require("./img/projentry.png"),
        version: VERSIONS.V2,
        updatedAt: "2021-11-06",
        tech: ["react", "antd"],
    },
    {
        title: "Loripsum generator",
        description: "Simple fish text generator",
        website: "https://loripsum-generator.vercel.app",
        source: "https://github.com/yesnoruly/loripsum-generator",
        preview: require("./img/loripsum-generator.png"),
        version: VERSIONS.V2,
        updatedAt: "2021-11-17",
        tech: ["react", "effector"],
    },
    {
        title: "Cast",
        description: "A podcast listening PWA with automated quality assurance",
        website: "https://cast-iu.pages.dev/",
        source: "https://github.com/aabounegm/cast",
        preview: require("./img/cast.png"),
        version: VERSIONS.V2,
        updatedAt: "2022-05-31",
        tech: ["svelte"],
    },
    {
        title: "Draw, I'll Help",
        description: "A drawing app with shape correction powered by ML",
        website: "https://illright.github.io/draw-ill-help/",
        source: "https://github.com/illright/draw-ill-help",
        preview: require("./img/draw-ill-help.png"),
        version: VERSIONS.V2,
        updatedAt: "2022-06-13",
        tech: ["svelte"],
    },
    {
        title: "Rastrr",
        description: "A simple and free graphic editor for novice artists",
        website: "https://rastrr.ru",
        source: "https://github.com/rastrr-editor/client",
        preview: require("./img/rastrr-editor.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-03-25",
        tech: ["svelte"],
    },
    {
        title: "Todo App (ReactNative+Redux)",
        description:
            "QuickStart todo-app example for ReactNative(Expo) developers",
        source: "https://github.com/berdimyradov/fs-rn-todo-app",
        preview: require("./img/fs-rn-todo-app.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-03-27",
        tech: ["react-native", "expo", "redux"],
    },
    {
        title: "Simple Greenhouse App (React+MobX)",
        description:
            "Simple demonstration of how FSD can be implemented with TypeScript, React.js, MobX and Firebase",
        source: "https://github.com/NIRumiantsev/feature-sliced-design",
        preview: require("./img/greenhouse.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-04-17",
        tech: ["react", "mobx", "typescript", "firebase", "mui", "vite"],
    },
    {
        title: "Nukeapp (React+ReduxToolkit)",
        description: "Shopping app build on React/ReduxToolkit stack",
        website: "https://nukeapp.netlify.app/",
        source: "https://github.com/noveogroup-amorgunov/nukeapp",
        preview: require("./img/nukeapp.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-04-24",
        tech: ["react", "redux-toolkit", "typescript", "vite"],
    },
    {
        title: "Sudoku (React+Effector)",
        description: "A simple crossword of numbers on effector / fsd",
        website: "https://sudoku-effector.pages.dev/",
        source: "https://github.com/Shiyan7/sudoku-effector",
        preview: require("./img/sudoku.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-06-08",
        tech: [
            "react",
            "effector",
            "typescript",
            "vite",
            "tailwind",
            "atomic-router",
        ],
    },
    {
        title: "Kinomore (React+Effector)",
        description: "Large project on the effector/fsd stack",
        website: "https://kinomore.netlify.app/",
        source: "https://github.com/Shiyan7/kinomore-v2",
        preview: require("./img/kinomore.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-07-10",
        tech: [
            "react",
            "effector",
            "typescript",
            "nextjs",
            "react-testing-library",
        ],
    },
    {
        title: "Conduit",
        description:
            "A social blogging site powered by Feature-Sliced Design architectural methodology.",
        website: "https://realworld-fsd.netlify.app/",
        source: "https://github.com/sldk-yuri/realworld-react-fsd",
        preview: require("./img/conduit.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-06-21",
        tech: [
            "react",
            "react-router",
            "react-query",
            "zustand",
            "vite",
            "typescript",
        ],
    },
    {
        title: "Todo app (Vue 3 + Pinia)",
        description:
            "QuickStart todo-app example for Vue developers with pinia store",
        website: "https://fsd-tasks.netlify.app/",
        source: "https://github.com/hoach-linux/fsd-vue-antd",
        preview: require("./img/todo-vue-pinia.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-010-12",
        tech: ["vue 3", "pinia", "vite", "typescript"],
    },
    {
        title: "E-Commerce",
        description:
            "This project is an online store built using React. It provides the ability to view the product catalog and product pages",
        website: "https://ruslan4432013.github.io/e-commerce-kts/",
        source: "https://github.com/ruslan4432013/e-commerce-kts",
        preview: require("./img/e-commerce.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-09-09",
        tech: ["react", "mobx", "webpack", "typescript", "ssr"],
    },
    {
        title: "Money Flow",
        description:
            "A mobile application for tracking your expenses and incomes.",
        source: "https://github.com/moneyflow-dev/moneyflow",
        preview: require("./img/moneyflow.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-09-07",
        tech: [
            "capacitorjs",
            "react",
            "react-router",
            "zustand",
            "vite",
            "typescript",
            "mobile",
            "android",
            "ios",
        ],
    },
    {
        title: "Сryptolight",
        description:
            "Cryptocurrency review site based on Feature-Sliced Design (Architectural methodology for frontend projects).",
        website: "http://crypto-light.space/",
        source: "https://github.com/Yar56/cryptolight",
        preview: require("./img/cryptolight.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-10-18",
        tech: ["react", "effector", "nextui", "typescript", "vite"],
    },
    {
        title: "VK Audiopad",
        description: "Chrome extension for VK Music",
        website:
            "https://chrome.google.com/webstore/detail/plclpmphdjmdgmdpfkcmdkmohgpfecip",
        source: "https://github.com/vissh/vkui-audiopad",
        preview: require("./img/vkaudiopad.png"),
        version: VERSIONS.V2,
        updatedAt: "2023-11-25",
        tech: ["react", "vkui", "typescript"],
    },
    {
        title: "Fake Cyber Web Store",
        description: "Example web store on Vue3",
        website: "https://akosogorov.github.io/fake-cyber-web-store/",
        source: "https://github.com/AKosogorov/fake-cyber-web-store",
        preview: require("./img/fake-cyber-web-store.jpg"),
        version: VERSIONS.V2,
        updatedAt: "2023-07-26",
        tech: [
            "vue3",
            "pinia",
            "typescript",
            "firebase",
            "vue-router",
            "eslint",
            "prettier",
            "vite",
        ],
    },
    {
        title: "Polka",
        description:
            "The application is a bookshelf where you can add your favorite books. The application works with the Google Books API.",
        website: "https://polka-fsd.netlify.app/",
        source: "https://github.com/lollipopfly/polka",
        preview: require("./img/polka.jpg"),
        version: VERSIONS.V2,
        updatedAt: "2023-12-06",
        tech: [
            "vue3",
            "pinia",
            "typescript",
            "vue-router",
            "eslint",
            "prettier",
            "vite",
            "vuetify",
        ],
    },
    {
        title: "FalkChat",
        description:
            "FalkChat is your go-to destination for seamless and engaging online conversations.",
        website: "https://chat.falkomer.tech",
        version: VERSIONS.V2,
        updatedAt: "2023-12-21",
        source: "https://github.com/falkomerr/falkchat",
        preview: require("./img/falkchat.png"),
        tech: [
            "react",
            "next",
            "prettier",
            "clerk",
            "typescript",
            "tailwind",
            "shadcn/ui",
            "zustand",
        ],
    },
    {
        title: "Posts (React Query example)",
        description:
            "Example of using FSD with React Query (Mutation, Query, Pagination)",
        website: "https://fsd-react-query-example.vercel.app/",
        version: VERSIONS.V2,
        updatedAt: "2024-02-25",
        source: "https://github.com/ruslan4432013/fsd-react-query-example",
        preview: require("./img/react-query-example.png"),
        tech: ["react", "react-query", "typescript", "material ui"],
    },
    {
        title: "Moonlogs (Effector + Forest example)",
        description:
            "Moonlogs is a business-event logging tool with a built-in user-friendly web interface for easy access to events",
        version: VERSIONS.V2,
        updatedAt: "2024-03-06",
        source: "https://github.com/pijng/moonlogs",
        preview: require("./img/moonlogs.png"),
        tech: ["forest", "effector", "tailwind", "typescript", "go"],
    },
    {
        title: "Moke Smoke (React Native example)",
        description:
            "An application that helps you quit smoking, published in the App Store and Google. Developed with React Native",
        version: VERSIONS.V2,
        updatedAt: "2024-03-31",
        source: "https://github.com/penteleichuk/Moke-Smoke",
        preview: require("./img/moke-smoke.jpg"),
        tech: ["react", "rtk", "persist", "typescript", "firebase"],
    },
    {
        title: "IT bookstore",
        description:
            "Catalog for viewing and searching information technology books",
        website: "https://umttikhinadasha.github.io/IT-Bookstore/",
        version: VERSIONS.V2,
        updatedAt: "2024-03-28",
        source: "https://github.com/UmttikhinaDasha/IT-Bookstore",
        preview: require("./img/it-bookstore.png"),
        tech: [
            "react",
            "redux toolkit",
            "typescript",
            "react router",
            "vite",
            "scss",
        ],
    },
    {
        title: "Roke.to dApp",
        description:
            "A crypto streaming service which allows paying people by the second",
        website: "https://app2.roke.to/",
        version: VERSIONS.V2,
        updatedAt: "2024-06-07",
        source: "https://github.com/roke-to/roketo-ui",
        preview: require("./img/roketo.jpg"),
        tech: ["react", "effector", "tailwindcss"],
    },
    {
        title: "Roke.to Business",
        description:
            "Business branch of Roketo, a crypto streaming service which allows paying people by the second",
        version: VERSIONS.V2,
        updatedAt: "2024-06-07",
        source: "https://github.com/roke-to/roketo-business-ui",
        preview: require("./img/roketo-business.jpg"),
        tech: ["react", "effector", "tailwindcss", "turbo"],
    },
    {
        title: "Ducks Tinder",
        description:
            "Tinder clone, application that helps you meet new people using matching, liking matches and finally chatting with them",
        website: "https://ducks-tinder-client.vercel.app/",
        version: VERSIONS.V2,
        updatedAt: "2024-06-28",
        source: "https://github.com/Stepasha419a/ducks-tinder-client",
        preview: require("./img/ducks-tinder.png"),
        tech: [
            "react",
            "redux toolkit",
            "typescript",
            "vite",
            "scss",
            "socket io",
        ],
    },
    // Reverse the list (last examples should be at the top)
].reverse();
